# Settings
title: Astral
tagline: by HTML5 UP
workTagline: Phasellus enim sapien, blandit ullamcorper elementum eu, condimentum eu elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia luctus elit eget interdum.
copyright: Untitled