# Settings
url: https://lufevida.github.io
baseurl: /html5up-astral
title: Astral
tagline: by HTML5 UP
photo: images/me.jpg
workTagline: Phasellus enim sapien, blandit ullamcorper elementum eu, condimentum eu elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia luctus elit eget interdum.
copyright: Untitled
email: you@provider.com
twitter: username
facebook: username
instagram: username